services:
    fastapi:
        build:
            context: ../..
            dockerfile: code/deployment/api/Dockerfile.fastapi
        container_name: fastapi
        ports:
            - "8000:8000"
        volumes:
            - ../../models:/app/models
        networks:
            - ml-network

    streamlit:
        build:
            context: ../..
            dockerfile: code/deployment/app/Dockerfile.streamlit
        container_name: streamlit
        ports:
            - "8501:8501"
        depends_on:
            - fastapi
        networks:
            - ml-network

networks:
    ml-network:
        driver: bridge